### ISSUE TITLE
Load selected country, states and cities when editing a post

### ISSUE THREAD

**Issue by dhmskrn** [Beee4life/acf-city-selector#21] opened 2018-07-21 09:51 UTC
Hi, I'm from Indonesia. I use your plugin and I'm very satisfied.

But, I found some (maybe) problems about your plugin. I will explain my problem..

1. I added an ACF City Selector to the field using the City Selector type (listed in the Options section). Then I added some states and cities to my database. And it works like a screenshot below.
![1](https://user-images.githubusercontent.com/5303741/43034312-6fe3b9c2-8d04-11e8-9b2d-72ef82700cdc.png)
**This post ID = 4015**

2. Then I click the Update button to update my post. That works, because ACF City Selector post meta has been saved in the database, like the screenshot below.
![2](https://user-images.githubusercontent.com/5303741/43034350-380cfc88-8d05-11e8-8326-6ce9894faad6.png)

3. But when I edit my post again, ACF City Selector does not show selected country, states and cities like the following screenshot.
![3](https://user-images.githubusercontent.com/5303741/43034384-978f5b1a-8d05-11e8-9220-7296edbaf040.png)

Please help me how to fix this problem. thanks.

**Comment by Beee4life** [comment] 2018-07-24 18:57
Have you tried it using with only the plugin active and a default Wordpress template ?

I have not been able to reproduce this.

Can you test this situation and report back ?

**Comment by dhmskrn** [comment] 2018-08-03 03:45
Now it works. This shows the selected country, states and cities like the following screenshot. But ACF City Selector is outside of Group Types.

![image](https://user-images.githubusercontent.com/5303741/43623126-c808ef3c-9709-11e8-8c46-8ebb38aa0ce2.png)

**Comment by Beee4life** [comment] 2018-08-03 09:29
What do you mean with it's "outside of Group Types" ?

**Comment by dhmskrn** [comment] 2018-08-03 17:41
I mean, I made a group type first, then added City Selector to it. Such as the following.

![image](https://user-images.githubusercontent.com/5303741/43656846-11222340-977e-11e8-97fa-f3572b73d5df.png)

If I don't use the group field like this, it works properly.
![image](https://user-images.githubusercontent.com/5303741/43657093-f18d15c0-977e-11e8-8e96-917b3a254b31.png)

**Comment by dhmskrn** [comment] 2018-08-03 17:42
do you understand what i mean?

**Comment by Beee4life** [comment] 2018-08-03 17:43
I think so, but I have never used the group field to be honest... so I also didn't test with it (yet) but I guess it's similar to adding it in a repeater, which does not work (yet).

**Comment by Beee4life** [comment] 2018-08-03 17:45
I have had a lot of things on my plate which were related to an event which is now behind me, so I hope to have some more time soon to spend on this and improve, since there are some other things I'd like to fix as well.

**Comment by Beee4life** [comment] 2020-05-02 16:59
@dhmskrn I released a beta release where this issue is 'fixed'. See [here](https://github.com/Beee4life/acf-city-selector/releases/tag/0.10-beta).

Official release will soon follow.

**Comment by Beee4life** [comment] 2020-05-03 21:53
@dhmskrn I just released the official release with support for groups. Please do read the readme to see which situations are not covered yet.

Will close this ticket for now. If a new issue comes up, please open a new issue.

**Closed by Beee4life** 2020-05-03 21:53 UTC
Labels: need more info
